apiVersion: batch/v1
kind: CronJob
metadata:
  name: cpu-reader-cj
  namespace: cpu-reader
spec:
  schedule: "*/1 * * * *" # Every 1 minute cronjob
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: ariko14/cpu_reader:latest
            env:
            - name: KAFKA_HOST
              value: "kafka.kafka:9092"
            - name: KAFKA_TOPIC
              value: "cpu_reader"
          restartPolicy: OnFailure